
version: '3'
services:
  data_ingestion:
    build: ./data_ingestion_service
    ports:
      - "8001:8000"
    volumes:
      - ./data:/app/data
  prediction:
    build: ./prediction_service
    ports:
      - "8002:8000"
    volumes:
      - ./data:/app/data
  notification:
    build: ./notification_service
    ports:
      - "8003:8000"
  db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=health_db
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
    